pre-commit:
  parallel: false
  commands:
    format:
      glob: "**/*.go"
      run: go tool gofumpt -w {staged_files}
      stage_fixed: true

    lint:
      run: make lint

    test:
      run: make test

skip_output:
  - meta
  - summary
