# Copyright © 2026 Michael Shields
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

pre-commit:
  parallel: false
  commands:
    format-go:
      glob: "**/*.go"
      run: go tool gofumpt -w {staged_files}
      stage_fixed: true

    format-prettier:
      glob: "**/*.{md,json,json5,yaml,yml}"
      run: ./tools/node_modules/.bin/prettier --write {staged_files}
      stage_fixed: true

    mod-tidy:
      glob: "go.mod"
      run: go mod tidy
      stage_fixed: true

    lint:
      run: make lint

    test:
      run: make test

skip_output:
  - meta
  - summary
